### ISSUE TITLE
Batch issue and job killed

### ISSUE THREAD

**Issue by leeanapeters** [immunogenomics/GeNA#1]
Hi, thank you all for the great package!

I have a couple of errors that I am encountering that I am unable to troubleshoot.

1) I am unable to use the batch variable to correct for batches even though batch is present in the d.samplem data frame
2) My job is being killed when run via the command line or through a slurm script, but I am not sure if this is a memory issue/ if the job should be consuming this amount of memory (~200GB for a dataset of ~100K cells and ~800K SNPs)

Here is the info on the commands/errors encountered, I appreciate any help you can offer!

./GeNA.sh -s /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/scDataObject1.h5ad -b 'False' -g /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/gtypes/merged_plink2_npod -o /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/ -c 'Age,Sex,Status'

Arguments provided:
Genotypes: /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/gtypes/merged_plink2_npod 
Single-cell data object: /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/scDataObject1.h5ad 
Output folder: /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/ 
Correct for batch: False 
Covariates: Age,Sex,Status
Values of k: Default

Formatting input for PLINK
/orange/brusko/leeanapeters/RIMA/miniconda3/envs/cytopus/lib/python3.8/site-packages/setuptools_scm/_integration/setuptools.py:30: RuntimeWarning: 
ERROR: setuptools==49.6.0 is used in combination with setuptools_scm>=8.x

Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=61

Suggested workaround if applicable:
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools

  warnings.warn(
plink2 --pfile /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/gtypes/merged_plink2_npod --pheno /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/nampcs.csv --glm --prune --out /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/plink_per_nampc/NAM
PLINK v2.00a2LM 64-bit Intel (12 Jul 2018)     www.cog-genomics.org/plink/2.0/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/plink_per_nampc/NAM.log.
Options in effect:
  --glm
  --out /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/plink_per_nampc/NAM
  --pfile /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/gtypes/merged_plink2_npod
  --pheno /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/nampcs.csv
  --require-pheno

Start time: Wed Nov 29 12:32:04 2023
514740 MiB RAM detected; reserving 257370 MiB for main workspace.
Using up to 64 threads (change this with --threads).
10 samples (0 females, 0 males, 10 ambiguous; 10 founders) loaded from
/blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/gtypes/merged_plink2_npod.psam.
891500 variants loaded from
/blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/gtypes/merged_plink2_npod.pvar.
4 quantitative phenotypes loaded.
--require-pheno: 0 samples removed.
10 samples (0 females, 0 males, 10 ambiguous; 10 founders) remaining after main
filters.
Calculating allele frequencies... done.
--glm: Skipping chrY since there are no males.
--glm linear regression on phenotype 'PC1': done.
Results written to /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/plink_per_nampc/NAM.PC1.glm.linear .
--glm linear regression on phenotype 'PC2': done.
Results written to /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/plink_per_nampc/NAM.PC2.glm.linear .
--glm linear regression on phenotype 'PC3': done.
Results written to /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/plink_per_nampc/NAM.PC3.glm.linear .
--glm linear regression on phenotype 'PC4': done.
Results written to /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/plink_per_nampc/NAM.PC4.glm.linear .
End time: Wed Nov 29 12:32:06 2023
Gathering metrics across NAM-PCs
Performing multi-NAM-PC tests
WARNING: ignoring environment value of R_HOME
./GeNA.sh: line 73: 1073608 Killed                  Rscript joint_test.R --outfile /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/P_k.txt --chisq_per_nampc_file /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/t_per_nampc.txt --ks_file /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/ks.csv
Assembling GeNA results file
paste: /blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/P_k.txt: No such file or directory
rm: cannot remove '/blue/brusko/leeanapeters/NS3305_1/out/dsb_doubletfinder_objects/geNA/output/P_k.txt': No such file or directory

**Comment by rumker** [comment]
Hi @leeanapeters, thank you for your interest in our tool!

For batch control:  It looks like your command has the -b flag set to 'False' — have you tried setting that flag to true?

It looks like your error message is coming from the stage in GeNA's workflow where joint association tests are performed per SNP across the full set of NAM-PCs. The format GeNA expects for the PLINK output per NAM-PC may not be generated by PLINK versions other than the one we require (2.00a2.3). Would you be able to confirm that is the version you are using? If the problem you are running into is a memory issue, it could be helpful to try a test run with a few thousand SNPs. (Our tutorial data might be helpful to you there!) Does GeNA run successfully with a small SNP set?

Please let me know if you're still running into trouble after trying these ideas and I'm happy to help further.

**Comment by leeanapeters** [comment]
Thank you so much or your quick reply!

Apologies I forgot to post the error with -b 'True', here it is:

Traceback (most recent call last):
  File "export_nampcs.py", line 24, in <module>
    cna.tl.nam(d, batches=d.samplem.batch, covs=args.covs, ks=[d.samplem.shape[0]])
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/cytopus/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'batch'


I will try regenerating the output with that version of plink first, I believe I may have been using a different plink2 version at the time. 

Thank you!!

**Comment by leeanapeters** [comment]
The versions we have installed on our cluster are plink/2.00a3LM and plink/2.00a2

When I load the former, it doesn't seem to recognize covariates, so I think I had loaded the correct version but not super familiar with the nomenclature

Error: --glm invoked without --covar/--covar-name/--covar-col-nums; this is
usually an analytical mistake.  Add the 'allow-no-covars' modifier if you are
sure you want this.

When running on 3000 filtered snps the command does complete with the latter plink version!

How do you recommend to get it to run with the full dataset?

Thanks!!

**Comment by rumker** [comment]
Hi @leeanapeters, thank you for sharing the output from your batch error. It looks like your batch information may not be stored in the single-cell object how GeNA expects: as a column named "batch" in d.samplem (where d is the MultiAnnData object variable name). If you load the data object provided to GeNA in python with d = cna.read(<path>) and examine d.samplem.batch, do you successfully access a numeric column that contains sample assignments to batches (0,0,...,1,1,...,2,2,...)?

I'm glad to hear you can run GeNA smoothly on a smaller set of SNPs! The commands we use to submit GeNA jobs to our clusters (via LSF though, not Slurm) are [here](https://github.com/immunogenomics/GeNA-applied/blob/main/run_gwas/01.OneK1K_GWAS.sh) and the corresponding log files [here](https://github.com/immunogenomics/GeNA-applied/blob/main/run_gwas/out/gwas_allcells.out) show the memory usage for testing ~6.4M SNPs in an object with ~800,000 cells. I'm not certain why your jobs seem to be requiring so much more memory, but I do have one idea that might be worth a try. If you've retained gene expression information per cell in your single-cell data object provided to GeNA, just loading that object could require a lot of memory. You could try saving a new copy of the data object in which you set d.raw = None and d.X=None (after generating your nearest neighbor graph). To verify whether loading the single-cell data object is the high-memory task or if your memory-use bottleneck is downstream, you could submit a job for a little python script that just loads the data object and see how much memory that takes. (And for comparison, you could run the same little script to load the reduced-size object.)

I hope these ideas help!

**Comment by leeanapeters** [comment]
Thanks for all those suggestions, that is really helpful!

So when I check d.samplem as a whole, I can see batch is there

However when I call d.samplem.batch it doesn't come up as a column

>>> d.samplem
             Age  Sex  Status  batch 
id                                   
6414       23.10    0       1       1
6418       24.86    0       1       1
6461       14.29    0       0       1
6482       18.69    1       0       1
6548_6548  20.24    0       0       2
6550_6550  25.06    0       1       2
6551_6551  20.70    0       1       2
6578_6578  11.95    1       1       2
6586_6586  13.21    0       0       2
6563_6563  14.56    1       1       2
>>> d.samplem.batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/cytopus/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'batch'


Is this some error in how I am defining batch or something?


Thanks!


Leeana

**Comment by rumker** [comment]
Ah, that's informative. What happens when you call d.samplem.columns? You'd want output that allows to you see the column names in quote marks, like ['Age', 'Sex', 'Status', 'batch'], which may be easiest to do interactively using ipython or a notebook. I wonder if there might be a sneaky whitespace character in your column name, like 'batch '. You could also try taking this object and setting d.samplem.columns=['Age', 'Sex', 'Status', 'batch'] then calling d.samplem.batch to see if the error is resolved.

**Comment by leeanapeters** [comment]
That was the problem!!
Index(['Age', 'Sex', 'Status', 'batch '], dtype='object')

I just renamed it to batch in the object and it ran successfully :)

I will try your ideas for running all snps now as well


Thank you for your help!!

**Comment by rumker** [comment]
Awesome! You're welcome!

**Comment by fruceslee** [comment]
Hi, thanks a lot for the nice software!

I performed the analysis using the tutorial data provided in the packages. I always get an error "Error: --glm invoked without --covar/--covar-name/--covar-col-nums".

"./GeNA.sh -s scDataObject.h5ad -b 'True' -g gtypes -o output/ -c 'Age,Sex,gPC1,gPC2,gPC3,gPC4,gPC5'
Arguments provided:
Genotypes: gtypes
Single-cell data object: scDataObject.h5ad
Output folder: output/
Correct for batch: True
Covariates: Age,Sex,gPC1,gPC2,gPC3,gPC4,gPC5
Values of k: Default

Formatting input for PLINK
plink2 --pfile gtypes --pheno output/nampcs.csv --glm --prune --out output/plink_per_nampc/NAM
PLINK v2.00a5.12LM 64-bit Intel (25 Jun 2024)  www.cog-genomics.org/plink/2.0/
(C) 2005-2024 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to output/plink_per_nampc/NAM.log.
Options in effect:
  --glm
  --out output/plink_per_nampc/NAM
  --pfile gtypes
  --pheno output/nampcs.csv
  --require-pheno

Start time: Wed Mar 26 10:45:06 2025
Error: --glm invoked without --covar/--covar-name/--covar-col-nums; this is
usually an analytical mistake.  Add the 'allow-no-covars' modifier if you are
sure you want this."

Do you have any suggestions about that? I have installed all the good versions for dependencies.

Best,

Lee
