### ISSUE TITLE
Recommendations for batch correction 

### ISSUE THREAD

**Issue by blake-bowen** [immunogenomics/GeNA#2]
Hi,

Thanks for the awesome tool. I have some questions about batch correction and would really appreciate if you had any advice :) 

1. My data are multiplexed, and includes samples that were sequenced in multiple batches, so there is a many-to-many relationship between batches and samples (ie. the same sample/donor can be in multiple different batches, and each batch contains multiple different donors), So I can't easily put this as a single "batch" column in `samplem`, while keeping `samplem` one row per sample. Is it possible to use  `-b 'True'` for this kind of study design?

2.  Is it possible/recommended to use Harmony batch corrected PC's for generating the neighbourhood graph upstream of making neighbourhood abundance matrix?

3. When running GeNA is there a benefit to running the in-built batch correction `-b 'True'` if I already used Harmony upstream?

**Comment by rumker** [comment]
Hi @blake-bowen, thank you for your interest in GeNA! 

When you want to control for a batch variable that does not take a single value per sample, I would definitely recommend applying a batch correction process upstream using a tool like Harmony. GeNA currently only accommodates a single batch variable that takes one value per sample. 

Exactly as you described, you can apply Harmony (or your batch correction tool of choice) upstream of GeNA and use the resulting hPCs to construct your nearest neighbor graph. GeNA expects an h5ad object with graph construction complete and will use the graph you provide to define neighborhoods. (GeNA looks for the object stored in d.uns["neighbors"]["connectivities"] or d.obsp["connectivities”] concordant with your anndata version.) 

For a batch variable that does take a single value per sample, meaning you could provide that variable to both Harmony and GeNA, the potential benefit of providing the variable to both tools is that each tool models the batch effect in a slightly different way. We have generally provided batch variables with this structure (one value per sample) to both tools. However, there may be instances when this strategy is overly conservative.

**Comment by blake-bowen** [comment]
Ok thanks!
