### ISSUE TITLE
Small P values output as zero 

### ISSUE THREAD

**Issue by blake-bowen** [immunogenomics/GeNA#3]
Hi,

I'm having an issue with P values for some associations output as zero in `sumstats.txt`.  My lowest non-zero P value is ~ 2.2e-16, and it looks like anything lower than this is maybe getting rounded to zero.

Is it possible to obtain P values lower than 2e-16 using GeNA? If so do you have any suggestions for what might be going wrong? 

Many thanks for your help! 
Blake

**Comment by rumker** [comment]
Hi @blake-bowen, I think this issue should be resolved in the most recent version of GeNA (committed July 26, 2024, "v1.0.0"). Can you share when you cloned the repo? Thank you!

**Comment by blake-bowen** [comment]
I did have the older version of GeNA installed so I have re-ran GeNA after updating to the latest version. It has helped partially solve the issue, however it looks like a small number of very significant associations where P < 1.2e-29 are still output as zero. My lowest P-value is 1.262177e-29.
Thanks so much for your help.

**Comment by rumker** [comment]
Thank you for flagging this! I have a hunch about the cause, but let me look into it and I’ll get back to you soon.

**Comment by rumker** [comment]
Hi @blake-bowen, I've updated the number of bits used to store these values and I believe this issue should be resolved now. Please let me know if you run into trouble even after pulling the latest version!

**Comment by blake-bowen** [comment]
Yes I just re-ran with the latest version and it's now resolved. Thank you!
